name: menu_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  get: ^4.6.6
  supabase_flutter: ^2.5.4
  freezed_annotation: ^2.4.1
  flutter_spinkit: ^5.2.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  readmore: ^3.0.0
  badges: ^3.1.2
  flutter_svg: ^2.0.10+1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true


  assets:
    # - images/
    - assets/image/
    - assets/svg/



  fonts:
    - family: RedditSansBlack
      fonts:
        - asset: font/RedditSans-Black.ttf
    - family: RedditSansBlackItalic
      fonts:
        - asset: font/RedditSans-BlackItalic.ttf
    - family: RedditSansBold
      fonts:
        - asset: font/RedditSans-Bold.ttf
    - family: RedditSansBoldItalic
      fonts:
        - asset: font/RedditSans-BoldItalic.ttf
    - family: RedditSansExtraBold
      fonts:
        - asset: font/RedditSans-ExtraBold.ttf
    - family: RedditSansExtraBoldItalic
      fonts:
        - asset: font/RedditSans-ExtraBoldItalic.ttf
    - family: RedditSansExtraLight
      fonts:
        - asset: font/RedditSans-ExtraLight.ttf
    - family: RedditSansExtraLightItalic
      fonts:
        - asset: font/RedditSans-ExtraLightItalic.ttf
    - family: RedditSansItalicVariableFont
      fonts:
        - asset: font/RedditSans-Italic-VariableFont_wght.ttf
    - family: RedditSansItalic
      fonts:
        - asset: font/RedditSans-Italic.ttf
    - family: RedditSansLight
      fonts:
        - asset: font/RedditSans-Light.ttf
    - family: RedditSansLightItalic
      fonts:
        - asset: font/RedditSans-LightItalic.ttf
    - family: RedditSansMedium
      fonts:
        - asset: font/RedditSans-Medium.ttf
    - family: RedditSansMediumItalic
      fonts:
        - asset: font/RedditSans-MediumItalic.ttf
    - family: RedditSansRegular
      fonts:
        - asset: font/RedditSans-Regular.ttf
    - family: RedditSansSemiBold
      fonts:
        - asset: font/RedditSans-SemiBold.ttf
    - family: RedditSansSemiBoldItalic
      fonts:
        - asset: font/RedditSans-SemiBoldItalic.ttf
    - family: RedditSansVariableFont
      fonts:
        - asset: font/RedditSans-VariableFont_wght.ttf
